account_id = "${CLOUDFLARE_ACCOUNT_ID}"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "cf_worker_status_page_pro", id = "${CLOUDFLARE_KV_NAMESPACE_ID}" } ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "cf_worker_status_page_pro", id = "${CLOUDFLARE_KV_NAMESPACE_ID}" } ]

[env.production.triggers]
crons = [
  "*/2 * * * *",
  "*/10 * * * *",
]
